# -*- coding: utf-8 -*-
"""Descriptive Statistics Case Study Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V__t7XeAhmUKKklBFVkcd_D9oHuRSAIU

###**Task1**:

Load and study the data
"""

#Loading libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Importing dataset

from google.colab import files
data = files.upload()

dt = pd.read_csv('Employee Dataset.csv')

dt.head()

dt.shape

dt.index

dt.columns

dt.info()



"""###**Observations from Task 1**:
There are 50 rows and 6 columnsin the data. Each row contains the employee specifics of a certain employee in the company.

The features in the data set are:



1.   The id of the employee
2.   Their respective groups and age
3.   Their healthy_eating and active_lifestyle
4.   Their salary
"""



"""###**Task 2**:
Visualise the Distributions of ratinghs and compensations
"""

#Create a scatter plot of the 'Age' and 'Employee salary' feature

plt.figure(figsize=(10,6))
plt.scatter(data = dt, x = 'age', y ='salary', color ='blue',
            edgecolor = 'linen', alpha = 0.5)

plt.title('Scatter Plot of Age vs Salary')
plt.xlabel('Age')
plt.ylabel('Salary')
plt.show()

"""**Observations**:
We observe that in general, there is a relationship between age and salary of employee.

As age increases, the salary also increases, tbough there are some outliers present as well
"""



#Create a scatter plot of the 'healthy_eating and 'actively_lifestyle'

plt.figure(figsize=(10,6))

sns.scatterplot(data = dt, x ='healthy_eating', y = 'active_lifestyle', color ='red', edgecolor = 'linen', alpha = 0.5)

plt.title('Scatter Plot of Healthy Eating vs Actively Lifestyle')
plt.xlabel('Healthy Eating')
plt.ylabel('Active Lifestyle')
plt.show()

"""###**Observations**:
We observe that in general, there is a relationship between healthy eating and active lifestyle of employee.

As healthy eating increases, the active lifestyle as increases
"""



##Create a scatter plot of the 'healthy_eating' and 'salary'

plt.figure(figsize=(10,6))

sns.scatterplot(data = dt, x ='healthy_eating', y = 'salary', color ='green',
                edgecolor = 'linen', alpha = 0.5)

plt.title('Scatter Plot of Healthy Eating vs Salary')
plt.xlabel('Healthy Eating')
plt.ylabel('Salary')
plt.show()

"""###**Observations**:
We observe that in general, there is a relationship between healthy_eating and salary of employee.

As healthy_eating increases, the salary also increases
"""



#Create a count plot of the 'groups'

plt.figure(figsize = (10,6))

sns.countplot(data = dt, x = 'groups', edgecolor = 'black', alpha = 0.7)

plt.title('Count Plot of Groups')
plt.xlabel('Groups')
plt.ylabel('Count')
plt.show()

"""**Observations**:
We see that most employees either belong to Group ! or Group ), with group A having maximum frequency
"""



#Create a histogram of the' salary

plt.figure(figsize = (10,6))

sns.histplot(data = dt, x = 'salary',color = 'orange',
             edgecolor = 'linen', alpha = 0.5, bins= 10)

plt.title('Histogram of Salary')
plt.xlabel('Salary')
plt.ylabel('Frequency')
plt.show()

"""**Observations**:
We can see that the salaries are not uniform, which is not necessarily a discrepancy

But we do observe that there are employees with salaries on either extremeties of the histogram.

Based on the hostogram, we can see that the count of the highest earning employee is veryt less

###**Observation from task 2**:


1.   Generally the employees age increase, there i an increase in the employee salary
2.   Generally as the employees healthy_eating habit increase, there is an increse in the employees salary as well
3.   However, the employee salry values are more spread out
4.   An employee of healthy_eating grater than 8 can be taken as 8 only
5.   An employee salary less than 1000 can be considered as lower salary
"""



"""###**Task 3**:
Subset the data based on threshold
"""

#Employee healthy_eating is greater than 8

sub1 = dt[dt['healthy_eating']> 8]
sub1

#salary less than 1000

sub2 = dt[dt['salary']< 1000]
sub2

#Employee with healthy_eating greater than 8 with salary less than 1000

sub = dt[(dt['healthy_eating']> 8) & (dt['salary']< 1000)]
sub

"""**Observations**:
The only employee seemingly facing a discrepancy in salary as compared to healthy eatings is employee id 26

The employee with id having 26 has salary of 700

###**Final Conclusion**:
From thge given data, we can use simple visualisation to get a sense of how data are distributed.

We can conduct primarily analysis simply by subsetting sata sets using well thought
"""

