# -*- coding: utf-8 -*-
"""Password_generator_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_ea6S1Hyy_AYH4PGdFr0vZe0JV4szKj
"""

import random

def passwordgenerator(length):
  char = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+"
  password = " "
  for elm in range(length):
    password = password + random.choice(char)

  return password

p1 = passwordgenerator(8)
print(p1)

p2 = passwordgenerator(12)
print(p2)













