# -*- coding: utf-8 -*-
"""Zomato_Data_Analysis_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPUJ_v0uB6ffV6bWiqu1tmT5UyzQfQW3

###**Zomato Data Analysis Using Python**

**Step 1:**  Import necessary Python libraries.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
data = files.upload()

"""**Step 2:** Create the data frame."""

df = pd.read_csv("Zomato-data-.csv")

df.head()

#Before proceeding, let’s convert the data type of the “rate” column to float and remove the denominator.

def handleRate(value):
  value = str(value).split('/')
  value = value[0]
  return float(value)

df['rate'] = df['rate'].apply(handleRate)

df.head()

#To obtain a summary of the data frame, you can use the following code

df.info()

#Let’s explore the listed_in (type) column

sns.countplot(x=df['listed_in(type)'], palette='viridis')
plt.xlabel('Type of Restaurant')
plt.ylabel('Count')
plt.show()
plt.show()

#Lets explore which type of restaurants are preferred

gd = df.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': gd})
plt.plot(result, c = 'green', marker = 'o')
plt.xlabel('Type of Restaurant', c= 'red', size = 20)
plt.ylabel('votes',c = 'red', size = 20)
plt.show()

#Now we will determine the restaurant’s name that received the maximum votes based on a given dataframe.

max_votes = df['votes'].max()
restaurants_with_max_votes = df.loc[df['votes'] == max_votes,
'name']

print("Restaurants with maximum votes:")
print(restaurants_with_max_votes)

#Let’s explore the online_order column

sns.countplot(x = df['online_order'])

#Let’s explore the rate column

plt.hist(df['rate'],bins = 5)
plt.title('Distribution of Ratings')
plt.xlabel('Rating')
plt.ylabel('Frequency')
plt.show()

#Let’s explore the approx_cost(for two people) column.

dt= df['approx_cost(for two people)']
sns.countplot(x = dt, palette = 'viridis')
plt.show()

#Now we will examine whether online orders receive higher ratings than offline orders.

plt.figure(figsize=(6,6))
sns.boxplot(x='online_order', y = 'rate', data = df, palette= 'viridis')
plt.show()

pd.pivot_table = df.pivot_table(index = 'listed_in(type)',
columns = 'online_order', aggfunc = 'size', fill_value=0)
sns.heatmap(pd.pivot_table, annot = True, cmap = 'viridis', fmt ='d')
plt.title('Distribution of Online Orders by Restaurant Type')
plt.xlabel('Online Order')
plt.ylabel('Restaurant Type')
plt.show()

"""###**Conclusion:**

Dining restaurants primarily accept offline orders, whereas cafes primarily receive online orders. This suggests that clients prefer to place orders in person at restaurants, but prefer online ordering at cafes.


"""